Delete from TCardType
Delete from TCardPropertyPara
Delete from TCardPropertyEnumValue
Delete from TCardField
Delete from TKey

SET IDENTITY_INSERT TCardPropertyPara ON

--INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)						
--VALUES(	1	,'所属项目','',	3	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	2	,'项目缩写','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	3	,'项目状态','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	4	,'计划开始时间','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	5	,'计划结束时间','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	6	,'计划工期','',4	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	7	,'项目控制阈值','',3	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	8	,'计划总人日','',3	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	9	,'项目经理','',6	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	10	,'实际开始时间','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	11	,'实际结束时间','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	12	,'实际工期','',4	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	13	,'实际总人日','',3	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	14	,'开发平台','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	15	,'开发语言','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	16	,'配置库类型','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	17	,'配置库路径','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	18	,'录入人','',6	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	19	,'需求调研人','',6	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	20	,'调研时间','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	21	,'调研对象','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	22	,'调研地点','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	23	,'优先级','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	24	,'所处阶段','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	25	,'需求类型','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	26	,'设计人','',6	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	27	,'录入时间','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	28	,'所属故事','',3	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	29	,'用例类型','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	30	,'期望结果','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	31	,'申请人','',6	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	32	,'审核人','',6	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	33	,'申请时间','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	34	,'完成时间','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	35	,'版本号','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	36	,'审核状态','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	37	,'是否标识版本','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	38	,'源代码路径','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	39	,'审核意见','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	40	,'Bug发生阶段','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	41	,'Bug发现阶段','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	42	,'发现人','',6	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	43	,'Bug状态','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	44	,'打开时间','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	45	,'关闭时间','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	46	,'bug优先级','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	47	,'可见级','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	48	,'严重性','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	49	,'发现版本','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	50	,'关闭版本','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	51	,'历史版本','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	52	,'用例编号','',3	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	53	,'复现步骤','',1	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	54	,'实际结果','',1	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	55	,'记录人','',6	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	56	,'会议日期','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	57	,'主持人','',6	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	58	,'持续时间','',3	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	59	,'会议参与人','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	60	,'会议缺席人','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	61	,'风险状态','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	62	,'发展趋势','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	63	,'提出人','',6	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	64	,'发生率','',3	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	65	,'影响人日','',3	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	66	,'风险优先级','',4	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	67	,'产生影响','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	68	,'减缓措施','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	69	,'应急措施','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	70	,'提交日期','',2	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	71	,'类型','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	72	,'是否在发布前','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	73	,'变更严重性','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	74	,'紧急性','',5	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	75	,'变更前的内容','',0	)
INSERT INTO TCardPropertyPara(PKID,[Name],Description,EnumCardPropertyDataType)	
VALUES(	76	,'变更后的内容','',0	)

SET IDENTITY_INSERT TCardPropertyPara OFF


SET IDENTITY_INSERT TCardPropertyEnumValue ON
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])										
VALUES(	1,'进行中',1,'#CC0000',3	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	2,'结项',2,'#00FF00',3	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	3,'1',1,'#000000',23	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	4,'2',2,'#000033',23	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	5,'3',3,'#000066',23	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	6,'4',4,'#000099',23	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	7,'5',5,'#0000CC',23	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	8,'6',6,'#0000FF',23	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	9,'7',7,'#0033CC',23	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	10,'8',8,'#0033FF',23	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	11,'9',9,'#0066FF',23	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	12,'10',10,'#0099FF',23	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	13,'需求调研阶段',1,'#000000',24	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	14,'需求分析阶段',2,'#CC0099',24	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	15,'设计阶段',3,'#FFCC33',24	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	16,'编码阶段',4,'#FF0000',24	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	17,'测试阶段',5,'#0000FF',24	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	18,'发布阶段',6,'#00CC00',24	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	19,'业务逻辑需求',1,'#006600',25	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	20,'用户界面需求',2,'#FF9900',25	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	21,'其它需求',3,'#CC0000',25	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	22,'接口-路径测试用例',1,'#ffffff',29	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	23,'功能测试用例',2,'#ffffff',29	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	24,'健壮性测试用例',3,'#ffffff',29	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	25,'性能测试用例',4,'#ffffff',29	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	26,'图形用户界面测试用例',5,'#ffffff',29	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	27,'信息安全性测试用例',6,'#ffffff',29	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	28,'压力测试用例',7,'#ffffff',29	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	29,'可靠性测试用例',8,'#ffffff',29	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	30,'安装/反安装测试用例',9,'#ffffff',29	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	31,'前期测试用例',10,'#ffffff',29	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	32,'待审核',1,'#ffffff',36	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	33,'通过审核',2,'#ffffff',36	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	34,'不通过审核',3,'#ffffff',36	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	35,'关闭',4,'#ffffff',36	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	36,'是',1,'#006600',37	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	37,'否',2,'#FFFF00',37	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	38,'需求调研阶段',1,'#ffffff',40	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	39,'需求分析阶段',2,'#ffffff',40	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	40,'设计阶段',3,'#ffffff',40	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	41,'编码阶段',4,'#ffffff',40	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	42,'测试阶段',5,'#ffffff',40	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	43,'发布阶段',6,'#ffffff',40	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	44,'需求调研阶段',1,'#ffffff',41	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	45,'需求分析阶段',2,'#ffffff',41	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	46,'设计阶段',3,'#ffffff',41	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	47,'编码阶段',4,'#ffffff',41	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	48,'测试阶段',5,'#ffffff',41	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	49,'发布阶段',6,'#ffffff',41	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	50,'打开',1,'#ffffff',43	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	51,'解决',2,'#ffffff',43	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	52,'重新打开',3,'#ffffff',43	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	53,'关闭',4,'#ffffff',43	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	54,'立即解决',1,'#ffffff',46	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	55,'高优先级',2,'#ffffff',46	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	56,'正常排队',3,'#ffffff',46	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	57,'低优先级',4,'#ffffff',46	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	58,'总是',1,'#ffffff',47	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	59,'通常',2,'#ffffff',47	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	60,'有时',3,'#ffffff',47	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	61,'很少',4,'#ffffff',47	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	62,'致命',1,'#ffffff',48	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	63,'严重',2,'#ffffff',48	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	64,'较严重',3,'#ffffff',48	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	65,'一般',4,'#ffffff',48	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	66,'较小',5,'#ffffff',48	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	67,'测试建议',6,'#ffffff',48	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	68,'未评估',1,'#ffffff',61	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	69,'打开',2,'#ffffff',61	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	70,'关闭',3,'#ffffff',61	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	71,'爆发',4,'#ffffff',61	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	72,'—',1,'#ffffff',62	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	73,'上升',2,'#ffffff',62	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	74,'下降',3,'#ffffff',62	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	75,'用户需求变更',1,'#0000FF',71	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	76,'系统需求变更',2,'#006633',71	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	77,'设计变更',3,'#CCCC00',71	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	78,'其他变更',4,'#CC0000',71	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	79,'是',1,'#FF0000',72	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	80,'否',2,'#00FF00',72	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	81,'紧急',1,'#CC0000',73	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	82,'较紧急',2,'#CC00CC',73	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	83,'中等',3,'#CC3300',73	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	84,'较轻微',4,'#FFCC00',73	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	85,'轻微',5,'#ffffff',73	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	86,'高',1,'#CC0000',74	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	87,'中',2,'#CC3300',74	)
INSERT INTO [TCardPropertyEnumValue]([PKID],[Name],[Order],[Color],[CardPropertyParaID])	
VALUES(	88,'低',3,'#CCCC00',74	)

SET IDENTITY_INSERT TCardPropertyEnumValue OFF


SET IDENTITY_INSERT TCardType ON
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(1, '项目卡片', '#000033', '')
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(2, '过程卡片', '#003366', '')
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(3, '用户故事卡片', '#006699', '')
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(4, '测试用例卡片', '#0099CC', '')
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(5, '测试申请卡片', '#00CCFF', '')
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(6, 'Bug卡片', '#99FF00', '')
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(7, '任务卡片', '#99CC33', '')
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(8, '会议卡片', '#999966', '')
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(9, '问题卡片', '#996699', '')
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(10, '风险卡片', '#9933CC', '')
INSERT INTO TCardType(pkid,[Name],Color,Description)
VALUES	(11, '变更卡片', '#9900FF', '')
SET IDENTITY_INSERT TCardType OFF

SET IDENTITY_INSERT TCardField ON
--INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])								
--VALUES(	1	,	1	,	1	,'',	1	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	2	,	2	,	1	,'',	2	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	3	,	3	,	1	,'',	3	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	4	,	4	,	1	,'',	4	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	5	,	5	,	1	,'',	5	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	6	,	6	,	1	,'',	6	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	7	,	7	,	1	,'',	7	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	8	,	8	,	1	,'',	8	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	9	,	9	,	1	,'',	9	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	10	,	10	,	1	,'',	10	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	11	,	11	,	1	,'',	11	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	12	,	12	,	1	,'',	12	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	13	,	13	,	1	,'',	13	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	14	,	14	,	1	,'',	14	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	15	,	15	,	1	,'',	15	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	16	,	16	,	1	,'',	16	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	17	,	17	,	1	,'',	17	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	18	,	18	,	3	,'',	1	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	19	,	19	,	3	,'',	2	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	20	,	20	,	3	,'',	3	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	21	,	21	,	3	,'',	4	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	22	,	22	,	3	,'',	5	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	23	,	23	,	3	,'',	6	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	24	,	24	,	3	,'',	7	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	25	,	25	,	3	,'',	8	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	26	,	26	,	4	,'',	1	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	27	,	27	,	4	,'',	2	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	28	,	28	,	4	,'',	3	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	29	,	29	,	4	,'',	4	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	30	,	30	,	4	,'',	5	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	31	,	31	,	5	,'',	1	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	32	,	32	,	5	,'',	2	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	33	,	33	,	5	,'',	3	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	34	,	34	,	5	,'',	4	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	35	,	35	,	5	,'',	5	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	36	,	36	,	5	,'',	6	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	37	,	37	,	5	,'',	7	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	38	,	38	,	5	,'',	8	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	39	,	39	,	5	,'',	9	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	40	,	40	,	6	,'',	1	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	41	,	41	,	6	,'',	2	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	42	,	42	,	6	,'',	3	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	43	,	43	,	6	,'',	4	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	44	,	44	,	6	,'',	5	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	45	,	45	,	6	,'',	6	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	46	,	46	,	6	,'',	7	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	47	,	47	,	6	,'',	8	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	48	,	48	,	6	,'',	9	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	49	,	49	,	6	,'',	10	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	50	,	50	,	6	,'',	11	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	51	,	51	,	6	,'',	12	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	52	,	52	,	6	,'',	13	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	53	,	53	,	6	,'',	14	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	54	,	54	,	6	,'',	15	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	55	,	55	,	8	,'',	1	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	56	,	56	,	8	,'',	2	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	57	,	57	,	8	,'',	3	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	58	,	58	,	8	,'',	4	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	59	,	59	,	8	,'',	5	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	60	,	60	,	8	,'',	6	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	61	,	61	,	10	,'',	1	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	62	,	62	,	10	,'',	2	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	63	,	63	,	10	,'',	3	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	64	,	64	,	10	,'',	4	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	65	,	65	,	10	,'',	5	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	66	,	66	,	10	,'',	6	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	67	,	67	,	10	,'',	7	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	68	,	68	,	10	,'',	8	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	69	,	69	,	10	,'',	9	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	70	,	70	,	11	,'',	1	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	71	,	71	,	11	,'',	2	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	72	,	72	,	11	,'',	3	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	73	,	73	,	11	,'',	4	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	74	,	74	,	11	,'',	5	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	75	,	75	,	11	,'',	6	)
INSERT INTO [TCardField]([PKID],[CardPropertyParaID],[CardTypeID],[FieldFormula],[Order])	
VALUES(	76	,	76	,	11	,'',	7	)
SET IDENTITY_INSERT TCardField OFF

SET IDENTITY_INSERT TKey ON

--INSERT INTO [TKey]([PKID],[TableName],[RowID])						
--VALUES(	1,'TCardPropertyPara',1	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	2,'TCardPropertyPara',2	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	3,'TCardPropertyPara',3	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	4,'TCardPropertyPara',4	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	5,'TCardPropertyPara',5	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	6,'TCardPropertyPara',6	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	7,'TCardPropertyPara',7	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	8,'TCardPropertyPara',8	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	9,'TCardPropertyPara',9	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	10,'TCardPropertyPara',10	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	11,'TCardPropertyPara',11	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	12,'TCardPropertyPara',12	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	13,'TCardPropertyPara',13	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	14,'TCardPropertyPara',14	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	15,'TCardPropertyPara',15	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	16,'TCardPropertyPara',16	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	17,'TCardPropertyPara',17	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	18,'TCardPropertyPara',18	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	19,'TCardPropertyPara',19	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	20,'TCardPropertyPara',20	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	21,'TCardPropertyPara',21	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	22,'TCardPropertyPara',22	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	23,'TCardPropertyPara',23	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	24,'TCardPropertyPara',24	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	25,'TCardPropertyPara',25	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	26,'TCardPropertyPara',26	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	27,'TCardPropertyPara',27	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	28,'TCardPropertyPara',28	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	29,'TCardPropertyPara',29	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	30,'TCardPropertyPara',30	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	31,'TCardPropertyPara',31	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	32,'TCardPropertyPara',32	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	33,'TCardPropertyPara',33	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	34,'TCardPropertyPara',34	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	35,'TCardPropertyPara',35	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	36,'TCardPropertyPara',36	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	37,'TCardPropertyPara',37	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	38,'TCardPropertyPara',38	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	39,'TCardPropertyPara',39	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	40,'TCardPropertyPara',40	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	41,'TCardPropertyPara',41	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	42,'TCardPropertyPara',42	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	43,'TCardPropertyPara',43	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	44,'TCardPropertyPara',44	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	45,'TCardPropertyPara',45	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	46,'TCardPropertyPara',46	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	47,'TCardPropertyPara',47	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	48,'TCardPropertyPara',48	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	49,'TCardPropertyPara',49	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	50,'TCardPropertyPara',50	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	51,'TCardPropertyPara',51	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	52,'TCardPropertyPara',52	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	53,'TCardPropertyPara',53	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	54,'TCardPropertyPara',54	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	55,'TCardPropertyPara',55	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	56,'TCardPropertyPara',56	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	57,'TCardPropertyPara',57	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	58,'TCardPropertyPara',58	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	59,'TCardPropertyPara',59	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	60,'TCardPropertyPara',60	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	61,'TCardPropertyPara',61	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	62,'TCardPropertyPara',62	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	63,'TCardPropertyPara',63	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	64,'TCardPropertyPara',64	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	65,'TCardPropertyPara',65	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	66,'TCardPropertyPara',66	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	67,'TCardPropertyPara',67	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	68,'TCardPropertyPara',68	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	69,'TCardPropertyPara',69	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	70,'TCardPropertyPara',70	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	71,'TCardPropertyPara',71	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	72,'TCardPropertyPara',72	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	73,'TCardPropertyPara',73	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	74,'TCardPropertyPara',74	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	75,'TCardPropertyPara',75	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	76,'TCardPropertyPara',76	)
INSERT INTO [TKey]([PKID],[TableName],[RowID])
VALUES(	77,'TCardPropertyEnumValue',1)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	78,'TCardPropertyEnumValue',2)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	79,'TCardPropertyEnumValue',3)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	80,'TCardPropertyEnumValue',4)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	81,'TCardPropertyEnumValue',5)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	82,'TCardPropertyEnumValue',6)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	83,'TCardPropertyEnumValue',7)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	84,'TCardPropertyEnumValue',8)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	85,'TCardPropertyEnumValue',9)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	86,'TCardPropertyEnumValue',10)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	87,'TCardPropertyEnumValue',11)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	88,'TCardPropertyEnumValue',12)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	89,'TCardPropertyEnumValue',13)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	90,'TCardPropertyEnumValue',14)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	91,'TCardPropertyEnumValue',15)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	92,'TCardPropertyEnumValue',16)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	93,'TCardPropertyEnumValue',17)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	94,'TCardPropertyEnumValue',18)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	95,'TCardPropertyEnumValue',19)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	96,'TCardPropertyEnumValue',20)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	97,'TCardPropertyEnumValue',21)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	98,'TCardPropertyEnumValue',22)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	99,'TCardPropertyEnumValue',23)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	100,'TCardPropertyEnumValue',24)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	101,'TCardPropertyEnumValue',25)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	102,'TCardPropertyEnumValue',26)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	103,'TCardPropertyEnumValue',27)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	104,'TCardPropertyEnumValue',28)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	105,'TCardPropertyEnumValue',29)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	106,'TCardPropertyEnumValue',30)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	107,'TCardPropertyEnumValue',31)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	108,'TCardPropertyEnumValue',32)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	109,'TCardPropertyEnumValue',33)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	110,'TCardPropertyEnumValue',34)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	111,'TCardPropertyEnumValue',35)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	112,'TCardPropertyEnumValue',36)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	113,'TCardPropertyEnumValue',37)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	114,'TCardPropertyEnumValue',38)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	115,'TCardPropertyEnumValue',39)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	116,'TCardPropertyEnumValue',40)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	117,'TCardPropertyEnumValue',41)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	118,'TCardPropertyEnumValue',42)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	119,'TCardPropertyEnumValue',43)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	120,'TCardPropertyEnumValue',44)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	121,'TCardPropertyEnumValue',45)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	122,'TCardPropertyEnumValue',46)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	123,'TCardPropertyEnumValue',47)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	124,'TCardPropertyEnumValue',48)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	125,'TCardPropertyEnumValue',49)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	126,'TCardPropertyEnumValue',50)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	127,'TCardPropertyEnumValue',51)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	128,'TCardPropertyEnumValue',52)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	129,'TCardPropertyEnumValue',53)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	130,'TCardPropertyEnumValue',54)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	131,'TCardPropertyEnumValue',55)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	132,'TCardPropertyEnumValue',56)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	133,'TCardPropertyEnumValue',57)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	134,'TCardPropertyEnumValue',58)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	135,'TCardPropertyEnumValue',59)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	136,'TCardPropertyEnumValue',60)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	137,'TCardPropertyEnumValue',61)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	138,'TCardPropertyEnumValue',62)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	139,'TCardPropertyEnumValue',63)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	140,'TCardPropertyEnumValue',64)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	141,'TCardPropertyEnumValue',65)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	142,'TCardPropertyEnumValue',66)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	143,'TCardPropertyEnumValue',67)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	144,'TCardPropertyEnumValue',68)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	145,'TCardPropertyEnumValue',69)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	146,'TCardPropertyEnumValue',70)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	147,'TCardPropertyEnumValue',71)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	148,'TCardPropertyEnumValue',72)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	149,'TCardPropertyEnumValue',73)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	150,'TCardPropertyEnumValue',74)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	151,'TCardPropertyEnumValue',75)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	152,'TCardPropertyEnumValue',76)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	153,'TCardPropertyEnumValue',77)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	154,'TCardPropertyEnumValue',78)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	155,'TCardPropertyEnumValue',79)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	156,'TCardPropertyEnumValue',80)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	157,'TCardPropertyEnumValue',81)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	158,'TCardPropertyEnumValue',82)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	159,'TCardPropertyEnumValue',83)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	160,'TCardPropertyEnumValue',84)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	161,'TCardPropertyEnumValue',85)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	162,'TCardPropertyEnumValue',86)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	163,'TCardPropertyEnumValue',87)
INSERT INTO [TKey]([PKID],[TableName],[RowID])	
VALUES(	164,'TCardPropertyEnumValue',88)	
SET IDENTITY_INSERT TKey OFF

declare @i int
declare @TCardTypeMax int
select @TCardTypeMax = Max(PKID) from TCardType
--declare @TCardFieldMax int
--select @TCardFieldMax = Max(PKID) from TCardField
set @i=0
while @i<@TCardTypeMax+1
  begin
	INSERT INTO [TKey]([TableName],[RowID])	
	select 'TCardType',pkid 
	from TCardType 
	where PKID=@i
	set @i=@i+1
  end

--set @i=0
--while @i<@TCardFieldMax+1
--  begin
--	INSERT INTO [TKey]([TableName],[RowID])	
--	select 'TCardField',pkid 
--	from TCardField 
--	where PKID=@i
--	set @i=@i+1
--  end
