//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP.Performance.Views.EmployeeStatistics {
    
    
    /// <summary>
    /// CommonStatisticsView 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class CommonStatisticsView {
        
        /// <summary>
        /// UpdatePanel1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        /// <summary>
        /// StatisticsConditionView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.StatisticsConditionView StatisticsConditionView1;
        
        /// <summary>
        /// OtherStatisticsDataView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.OtherStatisticsDataView OtherStatisticsDataView1;
        
        /// <summary>
        /// ComeAndLeaveTableView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.ComeAndLeaveTableView ComeAndLeaveTableView1;
        
        /// <summary>
        /// ComeAndLeaveBarChartView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.ComeAndLeaveBarChartView ComeAndLeaveBarChartView1;
        
        /// <summary>
        /// LeaveRateLineChartView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.LeaveRateLineChartView LeaveRateLineChartView1;
        
        /// <summary>
        /// GenderPieChartView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.GenderPieChartView GenderPieChartView1;
        
        /// <summary>
        /// EduBgPieChartView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.EduBgPieChartView EduBgPieChartView1;
        
        /// <summary>
        /// WorkAgePieChartView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.WorkAgePieChartView WorkAgePieChartView1;
        
        /// <summary>
        /// AgePieChartView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.AgePieChartView AgePieChartView1;
        
        /// <summary>
        /// WorkTypePieChartView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.WorkTypePieChartView WorkTypePieChartView1;
        
        /// <summary>
        /// PositionGradeTowerTableView1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::SEP.Performance.Views.EmployeeStatistics.PositionGradeTowerTableView PositionGradeTowerTableView1;
        
        /// <summary>
        /// UpdateProgress1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress UpdateProgress1;
    }
}
