this.Handlebars={};
(function(g){g.VERSION="1.0.rc.1";g.helpers={};g.partials={};g.registerHelper=function(h,c,e){if(e)c.not=e;this.helpers[h]=c};g.registerPartial=function(h,c){this.partials[h]=c};g.registerHelper("helperMissing",function(h){if(arguments.length!==2)throw new Error("Could not find property '"+h+"'");});var f=Object.prototype.toString;g.registerHelper("blockHelperMissing",function(h,c){var e=c.inverse||function(){},i=c.fn,a=f.call(h);if(a==="[object Function]")h=h.call(this);return h===true?i(this):h===
false||h==null?e(this):a==="[object Array]"?h.length>0?g.helpers.each(h,c):e(this):i(h)});g.K=function(){};g.createFrame=Object.create||function(h){g.K.prototype=h;h=new g.K;g.K.prototype=null;return h};g.registerHelper("each",function(h,c){var e=c.fn,i=c.inverse,a="",d;if(c.data)d=g.createFrame(c.data);if(h&&h.length>0){c=0;for(i=h.length;c<i;c++){if(d)d.index=c;a+=e(h[c],{data:d})}}else a=i(this);return a});g.registerHelper("if",function(h,c){if(f.call(h)==="[object Function]")h=h.call(this);return!h||
g.Utils.isEmpty(h)?c.inverse(this):c.fn(this)});g.registerHelper("unless",function(h,c){var e=c.fn;c.fn=c.inverse;c.inverse=e;return g.helpers["if"].call(this,h,c)});g.registerHelper("with",function(h,c){return c.fn(h)});g.registerHelper("log",function(h){g.log(h)})})(this.Handlebars);
var handlebars=function(){function g(){this.yy={}}var f={trace:function(){},yy:{},symbols_:{error:2,root:3,program:4,EOF:5,statements:6,simpleInverse:7,statement:8,openInverse:9,closeBlock:10,openBlock:11,mustache:12,partial:13,CONTENT:14,COMMENT:15,OPEN_BLOCK:16,inMustache:17,CLOSE:18,OPEN_INVERSE:19,OPEN_ENDBLOCK:20,path:21,OPEN:22,OPEN_UNESCAPED:23,OPEN_PARTIAL:24,params:25,hash:26,DATA:27,param:28,STRING:29,INTEGER:30,BOOLEAN:31,hashSegments:32,hashSegment:33,ID:34,EQUALS:35,pathSegments:36,SEP:37,
$accept:0,$end:1},terminals_:{2:"error",5:"EOF",14:"CONTENT",15:"COMMENT",16:"OPEN_BLOCK",18:"CLOSE",19:"OPEN_INVERSE",20:"OPEN_ENDBLOCK",22:"OPEN",23:"OPEN_UNESCAPED",24:"OPEN_PARTIAL",27:"DATA",29:"STRING",30:"INTEGER",31:"BOOLEAN",34:"ID",35:"EQUALS",37:"SEP"},productions_:[0,[3,2],[4,3],[4,1],[4,0],[6,1],[6,2],[8,3],[8,3],[8,1],[8,1],[8,1],[8,1],[11,3],[9,3],[10,3],[12,3],[12,3],[13,3],[13,4],[7,2],[17,3],[17,2],[17,2],[17,1],[17,1],[25,2],[25,1],[28,1],[28,1],[28,1],[28,1],[28,1],[26,1],[32,
2],[32,1],[33,3],[33,3],[33,3],[33,3],[33,3],[21,1],[36,3],[36,1]],performAction:function(c,e,i,a,d,b){c=b.length-1;switch(d){case 1:return b[c-1];case 2:this.$=new a.ProgramNode(b[c-2],b[c]);break;case 3:this.$=new a.ProgramNode(b[c]);break;case 4:this.$=new a.ProgramNode([]);break;case 5:this.$=[b[c]];break;case 6:b[c-1].push(b[c]);this.$=b[c-1];break;case 7:this.$=new a.BlockNode(b[c-2],b[c-1].inverse,b[c-1],b[c]);break;case 8:this.$=new a.BlockNode(b[c-2],b[c-1],b[c-1].inverse,b[c]);break;case 9:this.$=
b[c];break;case 10:this.$=b[c];break;case 11:this.$=new a.ContentNode(b[c]);break;case 12:this.$=new a.CommentNode(b[c]);break;case 13:this.$=new a.MustacheNode(b[c-1][0],b[c-1][1]);break;case 14:this.$=new a.MustacheNode(b[c-1][0],b[c-1][1]);break;case 15:this.$=b[c-1];break;case 16:this.$=new a.MustacheNode(b[c-1][0],b[c-1][1]);break;case 17:this.$=new a.MustacheNode(b[c-1][0],b[c-1][1],true);break;case 18:this.$=new a.PartialNode(b[c-1]);break;case 19:this.$=new a.PartialNode(b[c-2],b[c-1]);break;
case 20:break;case 21:this.$=[[b[c-2]].concat(b[c-1]),b[c]];break;case 22:this.$=[[b[c-1]].concat(b[c]),null];break;case 23:this.$=[[b[c-1]],b[c]];break;case 24:this.$=[[b[c]],null];break;case 25:this.$=[[new a.DataNode(b[c])],null];break;case 26:b[c-1].push(b[c]);this.$=b[c-1];break;case 27:this.$=[b[c]];break;case 28:this.$=b[c];break;case 29:this.$=new a.StringNode(b[c]);break;case 30:this.$=new a.IntegerNode(b[c]);break;case 31:this.$=new a.BooleanNode(b[c]);break;case 32:this.$=new a.DataNode(b[c]);
break;case 33:this.$=new a.HashNode(b[c]);break;case 34:b[c-1].push(b[c]);this.$=b[c-1];break;case 35:this.$=[b[c]];break;case 36:this.$=[b[c-2],b[c]];break;case 37:this.$=[b[c-2],new a.StringNode(b[c])];break;case 38:this.$=[b[c-2],new a.IntegerNode(b[c])];break;case 39:this.$=[b[c-2],new a.BooleanNode(b[c])];break;case 40:this.$=[b[c-2],new a.DataNode(b[c])];break;case 41:this.$=new a.IdNode(b[c]);break;case 42:b[c-2].push(b[c]);this.$=b[c-2];break;case 43:this.$=[b[c]];break}},table:[{3:1,4:2,
5:[2,4],6:3,8:4,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,11],22:[1,13],23:[1,14],24:[1,15]},{1:[3]},{5:[1,16]},{5:[2,3],7:17,8:18,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,19],20:[2,3],22:[1,13],23:[1,14],24:[1,15]},{5:[2,5],14:[2,5],15:[2,5],16:[2,5],19:[2,5],20:[2,5],22:[2,5],23:[2,5],24:[2,5]},{4:20,6:3,8:4,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,11],20:[2,4],22:[1,13],23:[1,14],24:[1,15]},{4:21,6:3,8:4,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,
11],20:[2,4],22:[1,13],23:[1,14],24:[1,15]},{5:[2,9],14:[2,9],15:[2,9],16:[2,9],19:[2,9],20:[2,9],22:[2,9],23:[2,9],24:[2,9]},{5:[2,10],14:[2,10],15:[2,10],16:[2,10],19:[2,10],20:[2,10],22:[2,10],23:[2,10],24:[2,10]},{5:[2,11],14:[2,11],15:[2,11],16:[2,11],19:[2,11],20:[2,11],22:[2,11],23:[2,11],24:[2,11]},{5:[2,12],14:[2,12],15:[2,12],16:[2,12],19:[2,12],20:[2,12],22:[2,12],23:[2,12],24:[2,12]},{17:22,21:23,27:[1,24],34:[1,26],36:25},{17:27,21:23,27:[1,24],34:[1,26],36:25},{17:28,21:23,27:[1,24],
34:[1,26],36:25},{17:29,21:23,27:[1,24],34:[1,26],36:25},{21:30,34:[1,26],36:25},{1:[2,1]},{6:31,8:4,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,11],22:[1,13],23:[1,14],24:[1,15]},{5:[2,6],14:[2,6],15:[2,6],16:[2,6],19:[2,6],20:[2,6],22:[2,6],23:[2,6],24:[2,6]},{17:22,18:[1,32],21:23,27:[1,24],34:[1,26],36:25},{10:33,20:[1,34]},{10:35,20:[1,34]},{18:[1,36]},{18:[2,24],21:41,25:37,26:38,27:[1,45],28:39,29:[1,42],30:[1,43],31:[1,44],32:40,33:46,34:[1,47],36:25},{18:[2,25]},{18:[2,41],27:[2,
41],29:[2,41],30:[2,41],31:[2,41],34:[2,41],37:[1,48]},{18:[2,43],27:[2,43],29:[2,43],30:[2,43],31:[2,43],34:[2,43],37:[2,43]},{18:[1,49]},{18:[1,50]},{18:[1,51]},{18:[1,52],21:53,34:[1,26],36:25},{5:[2,2],8:18,9:5,11:6,12:7,13:8,14:[1,9],15:[1,10],16:[1,12],19:[1,11],20:[2,2],22:[1,13],23:[1,14],24:[1,15]},{14:[2,20],15:[2,20],16:[2,20],19:[2,20],22:[2,20],23:[2,20],24:[2,20]},{5:[2,7],14:[2,7],15:[2,7],16:[2,7],19:[2,7],20:[2,7],22:[2,7],23:[2,7],24:[2,7]},{21:54,34:[1,26],36:25},{5:[2,8],14:[2,
8],15:[2,8],16:[2,8],19:[2,8],20:[2,8],22:[2,8],23:[2,8],24:[2,8]},{14:[2,14],15:[2,14],16:[2,14],19:[2,14],20:[2,14],22:[2,14],23:[2,14],24:[2,14]},{18:[2,22],21:41,26:55,27:[1,45],28:56,29:[1,42],30:[1,43],31:[1,44],32:40,33:46,34:[1,47],36:25},{18:[2,23]},{18:[2,27],27:[2,27],29:[2,27],30:[2,27],31:[2,27],34:[2,27]},{18:[2,33],33:57,34:[1,58]},{18:[2,28],27:[2,28],29:[2,28],30:[2,28],31:[2,28],34:[2,28]},{18:[2,29],27:[2,29],29:[2,29],30:[2,29],31:[2,29],34:[2,29]},{18:[2,30],27:[2,30],29:[2,30],
30:[2,30],31:[2,30],34:[2,30]},{18:[2,31],27:[2,31],29:[2,31],30:[2,31],31:[2,31],34:[2,31]},{18:[2,32],27:[2,32],29:[2,32],30:[2,32],31:[2,32],34:[2,32]},{18:[2,35],34:[2,35]},{18:[2,43],27:[2,43],29:[2,43],30:[2,43],31:[2,43],34:[2,43],35:[1,59],37:[2,43]},{34:[1,60]},{14:[2,13],15:[2,13],16:[2,13],19:[2,13],20:[2,13],22:[2,13],23:[2,13],24:[2,13]},{5:[2,16],14:[2,16],15:[2,16],16:[2,16],19:[2,16],20:[2,16],22:[2,16],23:[2,16],24:[2,16]},{5:[2,17],14:[2,17],15:[2,17],16:[2,17],19:[2,17],20:[2,17],
22:[2,17],23:[2,17],24:[2,17]},{5:[2,18],14:[2,18],15:[2,18],16:[2,18],19:[2,18],20:[2,18],22:[2,18],23:[2,18],24:[2,18]},{18:[1,61]},{18:[1,62]},{18:[2,21]},{18:[2,26],27:[2,26],29:[2,26],30:[2,26],31:[2,26],34:[2,26]},{18:[2,34],34:[2,34]},{35:[1,59]},{21:63,27:[1,67],29:[1,64],30:[1,65],31:[1,66],34:[1,26],36:25},{18:[2,42],27:[2,42],29:[2,42],30:[2,42],31:[2,42],34:[2,42],37:[2,42]},{5:[2,19],14:[2,19],15:[2,19],16:[2,19],19:[2,19],20:[2,19],22:[2,19],23:[2,19],24:[2,19]},{5:[2,15],14:[2,15],
15:[2,15],16:[2,15],19:[2,15],20:[2,15],22:[2,15],23:[2,15],24:[2,15]},{18:[2,36],34:[2,36]},{18:[2,37],34:[2,37]},{18:[2,38],34:[2,38]},{18:[2,39],34:[2,39]},{18:[2,40],34:[2,40]}],defaultActions:{16:[2,1],24:[2,25],38:[2,23],55:[2,21]},parseError:function(c){throw new Error(c);},parse:function(c){function e(){var s;s=i.lexer.lex()||1;if(typeof s!=="number")s=i.symbols_[s]||s;return s}var i=this,a=[0],d=[null],b=[],j=this.table,k="",l=0,q=0,r=0;this.lexer.setInput(c);this.lexer.yy=this.yy;this.yy.lexer=
this.lexer;this.yy.parser=this;if(typeof this.lexer.yylloc=="undefined")this.lexer.yylloc={};c=this.lexer.yylloc;b.push(c);var x=this.lexer.options&&this.lexer.options.ranges;if(typeof this.yy.parseError==="function")this.parseError=this.yy.parseError;for(var m,v,p,n,t={},u,o;;){p=a[a.length-1];if(this.defaultActions[p])n=this.defaultActions[p];else{if(m===null||typeof m=="undefined")m=e();n=j[p]&&j[p][m]}if(typeof n==="undefined"||!n.length||!n[0]){var w="";if(!r){o=[];for(u in j[p])this.terminals_[u]&&
u>2&&o.push("'"+this.terminals_[u]+"'");w=this.lexer.showPosition?"Parse error on line "+(l+1)+":\n"+this.lexer.showPosition()+"\nExpecting "+o.join(", ")+", got '"+(this.terminals_[m]||m)+"'":"Parse error on line "+(l+1)+": Unexpected "+(m==1?"end of input":"'"+(this.terminals_[m]||m)+"'");this.parseError(w,{text:this.lexer.match,token:this.terminals_[m]||m,line:this.lexer.yylineno,loc:c,expected:o})}}if(n[0]instanceof Array&&n.length>1)throw new Error("Parse Error: multiple actions possible at state: "+
p+", token: "+m);switch(n[0]){case 1:a.push(m);d.push(this.lexer.yytext);b.push(this.lexer.yylloc);a.push(n[1]);m=null;if(v){m=v;v=null}else{q=this.lexer.yyleng;k=this.lexer.yytext;l=this.lexer.yylineno;c=this.lexer.yylloc;r>0&&r--}break;case 2:o=this.productions_[n[1]][1];t.$=d[d.length-o];t._$={first_line:b[b.length-(o||1)].first_line,last_line:b[b.length-1].last_line,first_column:b[b.length-(o||1)].first_column,last_column:b[b.length-1].last_column};if(x)t._$.range=[b[b.length-(o||1)].range[0],
b[b.length-1].range[1]];p=this.performAction.call(t,k,q,l,this.yy,n[1],d,b);if(typeof p!=="undefined")return p;if(o){a=a.slice(0,-1*o*2);d=d.slice(0,-1*o);b=b.slice(0,-1*o)}a.push(this.productions_[n[1]][0]);d.push(t.$);b.push(t._$);n=j[a[a.length-2]][a[a.length-1]];a.push(n);break;case 3:return true}}return true}},h=function(){var c={EOF:1,parseError:function(e,i){if(this.yy.parser)this.yy.parser.parseError(e,i);else throw new Error(e);},setInput:function(e){this._input=e;this._more=this._less=this.done=
false;this.yylineno=this.yyleng=0;this.yytext=this.matched=this.match="";this.conditionStack=["INITIAL"];this.yylloc={first_line:1,first_column:0,last_line:1,last_column:0};if(this.options.ranges)this.yylloc.range=[0,0];this.offset=0;return this},input:function(){var e=this._input[0];this.yytext+=e;this.yyleng++;this.offset++;this.match+=e;this.matched+=e;if(e.match(/(?:\r\n?|\n).*/g)){this.yylineno++;this.yylloc.last_line++}else this.yylloc.last_column++;this.options.ranges&&this.yylloc.range[1]++;
this._input=this._input.slice(1);return e},unput:function(e){var i=e.length,a=e.split(/(?:\r\n?|\n)/g);this._input=e+this._input;this.yytext=this.yytext.substr(0,this.yytext.length-i-1);this.offset-=i;e=this.match.split(/(?:\r\n?|\n)/g);this.match=this.match.substr(0,this.match.length-1);this.matched=this.matched.substr(0,this.matched.length-1);if(a.length-1)this.yylineno-=a.length-1;var d=this.yylloc.range;this.yylloc={first_line:this.yylloc.first_line,last_line:this.yylineno+1,first_column:this.yylloc.first_column,
last_column:a?(a.length===e.length?this.yylloc.first_column:0)+e[e.length-a.length].length-a[0].length:this.yylloc.first_column-i};if(this.options.ranges)this.yylloc.range=[d[0],d[0]+this.yyleng-i];return this},more:function(){this._more=true;return this},less:function(e){this.unput(this.match.slice(e))},pastInput:function(){var e=this.matched.substr(0,this.matched.length-this.match.length);return(e.length>20?"...":"")+e.substr(-20).replace(/\n/g,"")},upcomingInput:function(){var e=this.match;if(e.length<
20)e+=this._input.substr(0,20-e.length);return(e.substr(0,20)+(e.length>20?"...":"")).replace(/\n/g,"")},showPosition:function(){var e=this.pastInput(),i=(new Array(e.length+1)).join("-");return e+this.upcomingInput()+"\n"+i+"^"},next:function(){if(this.done)return this.EOF;if(!this._input)this.done=true;var e,i,a;if(!this._more)this.match=this.yytext="";for(var d=this._currentRules(),b=0;b<d.length;b++)if((i=this._input.match(this.rules[d[b]]))&&(!e||i[0].length>e[0].length)){e=i;a=b;if(!this.options.flex)break}if(e){if(i=
e[0].match(/(?:\r\n?|\n).*/g))this.yylineno+=i.length;this.yylloc={first_line:this.yylloc.last_line,last_line:this.yylineno+1,first_column:this.yylloc.last_column,last_column:i?i[i.length-1].length-i[i.length-1].match(/\r?\n?/)[0].length:this.yylloc.last_column+e[0].length};this.yytext+=e[0];this.match+=e[0];this.matches=e;this.yyleng=this.yytext.length;if(this.options.ranges)this.yylloc.range=[this.offset,this.offset+=this.yyleng];this._more=false;this._input=this._input.slice(e[0].length);this.matched+=
e[0];e=this.performAction.call(this,this.yy,this,d[a],this.conditionStack[this.conditionStack.length-1]);if(this.done&&this._input)this.done=false;if(e)return e;else return}return this._input===""?this.EOF:this.parseError("Lexical error on line "+(this.yylineno+1)+". Unrecognized text.\n"+this.showPosition(),{text:"",token:null,line:this.yylineno})},lex:function(){var e=this.next();return typeof e!=="undefined"?e:this.lex()},begin:function(e){this.conditionStack.push(e)},popState:function(){return this.conditionStack.pop()},
_currentRules:function(){return this.conditions[this.conditionStack[this.conditionStack.length-1]].rules},topState:function(){return this.conditionStack[this.conditionStack.length-2]},pushState:function(e){this.begin(e)}};c.options={};c.performAction=function(e,i,a){switch(a){case 0:i.yytext.slice(-1)!=="\\"&&this.begin("mu");if(i.yytext.slice(-1)==="\\"){i.yytext=i.yytext.substr(0,i.yyleng-1);this.begin("emu")}if(i.yytext)return 14;break;case 1:return 14;case 2:i.yytext.slice(-1)!=="\\"&&this.popState();
if(i.yytext.slice(-1)==="\\")i.yytext=i.yytext.substr(0,i.yyleng-1);return 14;case 3:return 24;case 4:return 16;case 5:return 20;case 6:return 19;case 7:return 19;case 8:return 23;case 9:return 23;case 10:i.yytext=i.yytext.substr(3,i.yyleng-5);this.popState();return 15;case 11:return 22;case 12:return 35;case 13:return 34;case 14:return 34;case 15:return 37;case 16:break;case 17:this.popState();return 18;case 18:this.popState();return 18;case 19:i.yytext=i.yytext.substr(1,i.yyleng-2).replace(/\\"/g,
'"');return 29;case 20:i.yytext=i.yytext.substr(1,i.yyleng-2).replace(/\\"/g,'"');return 29;case 21:i.yytext=i.yytext.substr(1);return 27;case 22:return 31;case 23:return 31;case 24:return 30;case 25:return 34;case 26:i.yytext=i.yytext.substr(1,i.yyleng-2);return 34;case 27:return"INVALID";case 28:return 5}};c.rules=[/^(?:[^\x00]*?(?=(\{\{)))/,/^(?:[^\x00]+)/,/^(?:[^\x00]{2,}?(?=(\{\{|$)))/,/^(?:\{\{>)/,/^(?:\{\{#)/,/^(?:\{\{\/)/,/^(?:\{\{\^)/,/^(?:\{\{\s*else\b)/,/^(?:\{\{\{)/,/^(?:\{\{&)/,/^(?:\{\{![\s\S]*?\}\})/,
/^(?:\{\{)/,/^(?:=)/,/^(?:\.(?=[} ]))/,/^(?:\.\.)/,/^(?:[\/.])/,/^(?:\s+)/,/^(?:\}\}\})/,/^(?:\}\})/,/^(?:"(\\["]|[^"])*")/,/^(?:'(\\[']|[^'])*')/,/^(?:@[a-zA-Z]+)/,/^(?:true(?=[}\s]))/,/^(?:false(?=[}\s]))/,/^(?:[0-9]+(?=[}\s]))/,/^(?:[a-zA-Z0-9_$-]+(?=[=}\s\/.]))/,/^(?:\[[^\]]*\])/,/^(?:.)/,/^(?:$)/];c.conditions={mu:{rules:[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],inclusive:false},emu:{rules:[2],inclusive:false},INITIAL:{rules:[0,1,28],inclusive:true}};return c}();
f.lexer=h;g.prototype=f;f.Parser=g;return new g}();
if(typeof require!=="undefined"&&typeof exports!=="undefined"){exports.parser=handlebars;exports.Parser=handlebars.Parser;exports.parse=function(){return handlebars.parse.apply(handlebars,arguments)};exports.main=function(g){if(!g[1])throw new Error("Usage: "+g[0]+" FILE");g=typeof process!=="undefined"?require("fs").readFileSync(require("path").resolve(g[1]),"utf8"):require("file").path(require("file").cwd()).join(g[1]).read({charset:"utf-8"});return exports.parser.parse(g)};if(typeof module!=="undefined"&&
require.main===module)exports.main(typeof process!=="undefined"?process.argv.slice(1):require("system").args)}Handlebars.Parser=handlebars;Handlebars.parse=function(g){Handlebars.Parser.yy=Handlebars.AST;return Handlebars.Parser.parse(g)};Handlebars.print=function(g){return(new Handlebars.PrintVisitor).accept(g)};Handlebars.logger={DEBUG:0,INFO:1,WARN:2,ERROR:3,level:3,log:function(){}};Handlebars.log=function(g,f){Handlebars.logger.log(g,f)};
(function(){Handlebars.AST={};Handlebars.AST.ProgramNode=function(f,h){this.type="program";this.statements=f;if(h)this.inverse=new Handlebars.AST.ProgramNode(h)};Handlebars.AST.MustacheNode=function(f,h,c){this.type="mustache";this.escaped=!c;this.hash=h;c=this.id=f[0];f=this.params=f.slice(1);this.isHelper=(this.eligibleHelper=c.isSimple)&&(f.length||h)};Handlebars.AST.PartialNode=function(f,h){this.type="partial";this.id=f;this.context=h};var g=function(f,h){if(f.original!==h.original)throw new Handlebars.Exception(f.original+
" doesn't match "+h.original);};Handlebars.AST.BlockNode=function(f,h,c,e){g(f.id,e);this.type="block";this.mustache=f;this.program=h;if((this.inverse=c)&&!this.program)this.isInverse=true};Handlebars.AST.ContentNode=function(f){this.type="content";this.string=f};Handlebars.AST.HashNode=function(f){this.type="hash";this.pairs=f};Handlebars.AST.IdNode=function(f){this.type="ID";this.original=f.join(".");for(var h=[],c=0,e=0,i=f.length;e<i;e++){var a=f[e];if(a==="..")c++;else if(a==="."||a==="this")this.isScoped=
true;else h.push(a)}this.parts=h;this.string=h.join(".");this.depth=c;this.isSimple=f.length===1&&!this.isScoped&&c===0};Handlebars.AST.DataNode=function(f){this.type="DATA";this.id=f};Handlebars.AST.StringNode=function(f){this.type="STRING";this.string=f};Handlebars.AST.IntegerNode=function(f){this.type="INTEGER";this.integer=f};Handlebars.AST.BooleanNode=function(f){this.type="BOOLEAN";this.bool=f};Handlebars.AST.CommentNode=function(f){this.type="comment";this.comment=f}})();
Handlebars.Exception=function(){var g=Error.prototype.constructor.apply(this,arguments);for(var f in g)if(g.hasOwnProperty(f))this[f]=g[f];this.message=g.message};Handlebars.Exception.prototype=new Error;Handlebars.SafeString=function(g){this.string=g};Handlebars.SafeString.prototype.toString=function(){return this.string.toString()};
(function(){var g={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","`":"&#x60;"},f=/[&<>"'`]/g,h=/[&<>"'`]/,c=function(e){return g[e]||"&amp;"};Handlebars.Utils={escapeExpression:function(e){if(e instanceof Handlebars.SafeString)return e.toString();else if(e==null||e===false)return"";if(!h.test(e))return e;return e.replace(f,c)},isEmpty:function(e){return typeof e==="undefined"?true:e===null?true:e===false?true:Object.prototype.toString.call(e)==="[object Array]"&&e.length===0?true:false}}})();
Handlebars.Compiler=function(){};Handlebars.JavaScriptCompiler=function(){};
(function(g,f){g.prototype={compiler:g,disassemble:function(){for(var a=this.opcodes,d,b=[],j,k,l=0,q=a.length;l<q;l++){d=a[l];if(d.opcode==="DECLARE")b.push("DECLARE "+d.name+"="+d.value);else{j=[];for(var r=0;r<d.args.length;r++){k=d.args[r];if(typeof k==="string")k='"'+k.replace("\n","\\n")+'"';j.push(k)}b.push(d.opcode+" "+j.join(" "))}}return b.join("\n")},guid:0,compile:function(a,d){this.children=[];this.depths={list:[]};this.options=d;d=this.options.knownHelpers;this.options.knownHelpers=
{helperMissing:true,blockHelperMissing:true,each:true,"if":true,unless:true,"with":true,log:true};if(d)for(var b in d)this.options.knownHelpers[b]=d[b];return this.program(a)},accept:function(a){return this[a.type](a)},program:function(a){a=a.statements;var d;this.opcodes=[];for(var b=0,j=a.length;b<j;b++){d=a[b];this[d.type](d)}this.isSimple=j===1;this.depths.list=this.depths.list.sort(function(k,l){return k-l});return this},compileProgram:function(a){a=(new this.compiler).compile(a,this.options);
var d=this.guid++,b;this.usePartial=this.usePartial||a.usePartial;this.children[d]=a;for(var j=0,k=a.depths.list.length;j<k;j++){b=a.depths.list[j];b<2||this.addDepth(b-1)}return d},block:function(a){var d=a.mustache,b=a.program;a=a.inverse;if(b)b=this.compileProgram(b);if(a)a=this.compileProgram(a);var j=this.classifyMustache(d);if(j==="helper")this.helperMustache(d,b,a);else if(j==="simple"){this.simpleMustache(d);this.opcode("pushProgram",b);this.opcode("pushProgram",a);this.opcode("pushLiteral",
"{}");this.opcode("blockValue")}else{this.ambiguousMustache(d,b,a);this.opcode("pushProgram",b);this.opcode("pushProgram",a);this.opcode("pushLiteral","{}");this.opcode("ambiguousBlockValue")}this.opcode("append")},hash:function(a){a=a.pairs;var d,b;this.opcode("push","{}");for(var j=0,k=a.length;j<k;j++){d=a[j];b=d[1];this.accept(b);this.opcode("assignToHash",d[0])}},partial:function(a){var d=a.id;this.usePartial=true;a.context?this.ID(a.context):this.opcode("push","depth0");this.opcode("invokePartial",
d.original);this.opcode("append")},content:function(a){this.opcode("appendContent",a.string)},mustache:function(a){var d=this.options,b=this.classifyMustache(a);if(b==="simple")this.simpleMustache(a);else b==="helper"?this.helperMustache(a):this.ambiguousMustache(a);a.escaped&&!d.noEscape?this.opcode("appendEscaped"):this.opcode("append")},ambiguousMustache:function(a,d,b){a=a.id;var j=a.parts[0];this.opcode("getContext",a.depth);this.opcode("pushProgram",d);this.opcode("pushProgram",b);this.opcode("invokeAmbiguous",
j)},simpleMustache:function(a){a=a.id;if(a.type==="DATA")this.DATA(a);else if(a.parts.length)this.ID(a);else{this.addDepth(a.depth);this.opcode("getContext",a.depth);this.opcode("pushContext")}this.opcode("resolvePossibleLambda")},helperMustache:function(a,d,b){d=this.setupFullMustacheParams(a,d,b);a=a.id.parts[0];if(this.options.knownHelpers[a])this.opcode("invokeKnownHelper",d.length,a);else if(this.knownHelpersOnly)throw new Error("You specified knownHelpersOnly, but used the unknown helper "+
a);else this.opcode("invokeHelper",d.length,a)},ID:function(a){this.addDepth(a.depth);this.opcode("getContext",a.depth);a.parts[0]?this.opcode("lookupOnContext",a.parts[0]):this.opcode("pushContext");for(var d=1,b=a.parts.length;d<b;d++)this.opcode("lookup",a.parts[d])},DATA:function(a){this.options.data=true;this.opcode("lookupData",a.id)},STRING:function(a){this.opcode("pushString",a.string)},INTEGER:function(a){this.opcode("pushLiteral",a.integer)},BOOLEAN:function(a){this.opcode("pushLiteral",
a.bool)},comment:function(){},opcode:function(a){this.opcodes.push({opcode:a,args:[].slice.call(arguments,1)})},declare:function(a,d){this.opcodes.push({opcode:"DECLARE",name:a,value:d})},addDepth:function(a){if(isNaN(a))throw new Error("EWOT");if(a!==0)if(!this.depths[a]){this.depths[a]=true;this.depths.list.push(a)}},classifyMustache:function(a){var d=a.isHelper,b=a.eligibleHelper,j=this.options;if(b&&!d)if(j.knownHelpers[a.id.parts[0]])d=true;else if(j.knownHelpersOnly)b=false;return d?"helper":
b?"ambiguous":"simple"},pushParams:function(a){for(var d=a.length,b;d--;){b=a[d];if(this.options.stringParams){b.depth&&this.addDepth(b.depth);this.opcode("getContext",b.depth||0);this.opcode("pushStringParam",b.string)}else this[b.type](b)}},setupMustacheParams:function(a){var d=a.params;this.pushParams(d);a.hash?this.hash(a.hash):this.opcode("pushLiteral","{}");return d},setupFullMustacheParams:function(a,d,b){var j=a.params;this.pushParams(j);this.opcode("pushProgram",d);this.opcode("pushProgram",
b);a.hash?this.hash(a.hash):this.opcode("pushLiteral","{}");return j}};var h=function(a){this.value=a};f.prototype={nameLookup:function(a,d){return/^[0-9]+$/.test(d)?a+"["+d+"]":f.isValidJavaScriptVariableName(d)?a+"."+d:a+"['"+d+"']"},appendToBuffer:function(a){return this.environment.isSimple?"return "+a+";":"buffer += "+a+";"},initializeBuffer:function(){return this.quotedString("")},namespace:"Handlebars",compile:function(a,d,b,j){this.environment=a;this.options=d||{};Handlebars.log(Handlebars.logger.DEBUG,
this.environment.disassemble()+"\n\n");this.name=this.environment.name;this.isChild=!!b;this.context=b||{programs:[],aliases:{}};this.preamble();this.stackSlot=0;this.stackVars=[];this.registers={list:[]};this.compileStack=[];this.compileChildren(a,d);a=a.opcodes;this.i=0;for(i=a.length;this.i<i;this.i++){d=a[this.i];if(d.opcode==="DECLARE")this[d.name]=d.value;else this[d.opcode].apply(this,d.args)}return this.createFunctionContext(j)},nextOpcode:function(){return this.environment.opcodes[this.i+
1]},eat:function(){this.i+=1},preamble:function(){var a=[];if(this.isChild)a.push("");else{var d=this.namespace,b="helpers = helpers || "+d+".helpers;";if(this.environment.usePartial)b=b+" partials = partials || "+d+".partials;";if(this.options.data)b+=" data = data || {};";a.push(b)}this.environment.isSimple?a.push(""):a.push(", buffer = "+this.initializeBuffer());this.lastContext=0;this.source=a},createFunctionContext:function(a){var d=this.stackVars.concat(this.registers.list);if(d.length>0)this.source[1]=
this.source[1]+", "+d.join(", ");if(!this.isChild)for(var b in this.context.aliases)this.source[1]=this.source[1]+", "+b+"="+this.context.aliases[b];if(this.source[1])this.source[1]="var "+this.source[1].substring(2)+";";this.isChild||(this.source[1]+="\n"+this.context.programs.join("\n")+"\n");this.environment.isSimple||this.source.push("return buffer;");d=this.isChild?["depth0","data"]:["Handlebars","depth0","helpers","partials","data"];b=0;for(var j=this.environment.depths.list.length;b<j;b++)d.push("depth"+
this.environment.depths.list[b]);if(a){d.push(this.source.join("\n  "));return Function.apply(this,d)}else{a="function "+(this.name||"")+"("+d.join(",")+") {\n  "+this.source.join("\n  ")+"}";Handlebars.log(Handlebars.logger.DEBUG,a+"\n\n");return a}},blockValue:function(){this.context.aliases.blockHelperMissing="helpers.blockHelperMissing";var a=["depth0"];this.setupParams(0,a);this.replaceStack(function(d){a.splice(1,0,d);return d+" = blockHelperMissing.call("+a.join(", ")+")"})},ambiguousBlockValue:function(){this.context.aliases.blockHelperMissing=
"helpers.blockHelperMissing";var a=["depth0"];this.setupParams(0,a);var d=this.topStack();a.splice(1,0,d);this.source.push("if (!"+this.lastHelper+") { "+d+" = blockHelperMissing.call("+a.join(", ")+"); }")},appendContent:function(a){this.source.push(this.appendToBuffer(this.quotedString(a)))},append:function(){var a=this.popStack();this.source.push("if("+a+" || "+a+" === 0) { "+this.appendToBuffer(a)+" }");this.environment.isSimple&&this.source.push("else { "+this.appendToBuffer("''")+" }")},appendEscaped:function(){var a=
this.nextOpcode(),d="";this.context.aliases.escapeExpression="this.escapeExpression";if(a&&a.opcode==="appendContent"){d=" + "+this.quotedString(a.args[0]);this.eat(a)}this.source.push(this.appendToBuffer("escapeExpression("+this.popStack()+")"+d))},getContext:function(a){if(this.lastContext!==a)this.lastContext=a},lookupOnContext:function(a){this.pushStack(this.nameLookup("depth"+this.lastContext,a,"context"))},pushContext:function(){this.pushStackLiteral("depth"+this.lastContext)},resolvePossibleLambda:function(){this.context.aliases.functionType=
'"function"';this.replaceStack(function(a){return"typeof "+a+" === functionType ? "+a+"() : "+a})},lookup:function(a){this.replaceStack(function(d){return d+" == null || "+d+" === false ? "+d+" : "+this.nameLookup(d,a,"context")})},lookupData:function(a){this.pushStack(this.nameLookup("data",a,"data"))},pushStringParam:function(a){this.pushStackLiteral("depth"+this.lastContext);this.pushString(a)},pushString:function(a){this.pushStackLiteral(this.quotedString(a))},push:function(a){this.pushStack(a)},
pushLiteral:function(a){this.pushStackLiteral(a)},pushProgram:function(a){a!=null?this.pushStackLiteral(this.programExpression(a)):this.pushStackLiteral(null)},invokeHelper:function(a,d){this.context.aliases.helperMissing="helpers.helperMissing";a=this.lastHelper=this.setupHelper(a,d);this.register("foundHelper",a.name);this.pushStack("foundHelper ? foundHelper.call("+a.callParams+") : helperMissing.call("+a.helperMissingParams+")")},invokeKnownHelper:function(a,d){a=this.setupHelper(a,d);this.pushStack(a.name+
".call("+a.callParams+")")},invokeAmbiguous:function(a){this.context.aliases.functionType='"function"';this.pushStackLiteral("{}");var d=this.setupHelper(0,a);this.register("foundHelper",this.lastHelper=this.nameLookup("helpers",a,"helper"));a=this.nameLookup("depth"+this.lastContext,a,"context");var b=this.nextStack();this.source.push("if (foundHelper) { "+b+" = foundHelper.call("+d.callParams+"); }");this.source.push("else { "+b+" = "+a+"; "+b+" = typeof "+b+" === functionType ? "+b+"() : "+b+"; }")},
invokePartial:function(a){a=[this.nameLookup("partials",a,"partial"),"'"+a+"'",this.popStack(),"helpers","partials"];this.options.data&&a.push("data");this.context.aliases.self="this";this.pushStack("self.invokePartial("+a.join(", ")+");")},assignToHash:function(a){var d=this.popStack();this.source.push(this.topStack()+"['"+a+"'] = "+d+";")},compiler:f,compileChildren:function(a,d){a=a.children;for(var b,j,k=0,l=a.length;k<l;k++){b=a[k];j=new this.compiler;this.context.programs.push("");var q=this.context.programs.length;
b.index=q;b.name="program"+q;this.context.programs[q]=j.compile(b,d,this.context)}},programExpression:function(a){this.context.aliases.self="this";if(a==null)return"self.noop";var d=this.environment.children[a];a=d.depths.list;for(var b=[d.index,d.name,"data"],j=0,k=a.length;j<k;j++){d=a[j];d===1?b.push("depth0"):b.push("depth"+(d-1))}if(a.length===0)return"self.program("+b.join(", ")+")";else{b.shift();return"self.programWithDepth("+b.join(", ")+")"}},register:function(a,d){this.useRegister(a);this.source.push(a+
" = "+d+";")},useRegister:function(a){if(!this.registers[a]){this.registers[a]=true;this.registers.list.push(a)}},pushStackLiteral:function(a){this.compileStack.push(new h(a));return a},pushStack:function(a){this.source.push(this.incrStack()+" = "+a+";");this.compileStack.push("stack"+this.stackSlot);return"stack"+this.stackSlot},replaceStack:function(a){a=a.call(this,this.topStack());this.source.push(this.topStack()+" = "+a+";");return"stack"+this.stackSlot},nextStack:function(){var a=this.incrStack();
this.compileStack.push("stack"+this.stackSlot);return a},incrStack:function(){this.stackSlot++;this.stackSlot>this.stackVars.length&&this.stackVars.push("stack"+this.stackSlot);return"stack"+this.stackSlot},popStack:function(){var a=this.compileStack.pop();if(a instanceof h)return a.value;else{this.stackSlot--;return a}},topStack:function(){var a=this.compileStack[this.compileStack.length-1];return a instanceof h?a.value:a},quotedString:function(a){return'"'+a.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\n/g,
"\\n").replace(/\r/g,"\\r")+'"'},setupHelper:function(a,d){var b=[];this.setupParams(a,b);a=this.nameLookup("helpers",d,"helper");return{params:b,name:a,callParams:["depth0"].concat(b).join(", "),helperMissingParams:["depth0",this.quotedString(d)].concat(b).join(", ")}},setupParams:function(a,d){var b=[],j=[],k,l;b.push("hash:"+this.popStack());k=this.popStack();if((l=this.popStack())||k){if(!l){this.context.aliases.self="this";l="self.noop"}if(!k){this.context.aliases.self="this";k="self.noop"}b.push("inverse:"+
k);b.push("fn:"+l)}for(l=0;l<a;l++){k=this.popStack();d.push(k);this.options.stringParams&&j.push(this.popStack())}this.options.stringParams&&b.push("contexts:["+j.join(",")+"]");this.options.data&&b.push("data:data");d.push("{"+b.join(",")+"}");return d.join(", ")}};g="break else new var case finally return void catch for switch while continue function this with default if throw delete in try do instanceof typeof abstract enum int short boolean export interface static byte extends long super char final native synchronized class float package throws const goto private transient debugger implements protected volatile double import public let yield".split(" ");
for(var c=f.RESERVED_WORDS={},e=0,i=g.length;e<i;e++)c[g[e]]=true;f.isValidJavaScriptVariableName=function(a){if(!f.RESERVED_WORDS[a]&&/^[a-zA-Z_$][0-9a-zA-Z_$]+$/.test(a))return true;return false}})(Handlebars.Compiler,Handlebars.JavaScriptCompiler);Handlebars.precompile=function(g,f){f=f||{};g=Handlebars.parse(g);g=(new Handlebars.Compiler).compile(g,f);return(new Handlebars.JavaScriptCompiler).compile(g,f)};
Handlebars.compile=function(g,f){function h(){var e=Handlebars.parse(g);e=(new Handlebars.Compiler).compile(e,f);e=(new Handlebars.JavaScriptCompiler).compile(e,f,undefined,true);return Handlebars.template(e)}f=f||{};var c;return function(e,i){c||(c=h());return c.call(this,e,i)}};
Handlebars.VM={template:function(g){var f={escapeExpression:Handlebars.Utils.escapeExpression,invokePartial:Handlebars.VM.invokePartial,programs:[],program:function(h,c,e){var i=this.programs[h];if(e)return Handlebars.VM.program(c,e);else{i||(i=this.programs[h]=Handlebars.VM.program(c));return i}},programWithDepth:Handlebars.VM.programWithDepth,noop:Handlebars.VM.noop};return function(h,c){c=c||{};return g.call(f,Handlebars,h,c.helpers,c.partials,c.data)}},programWithDepth:function(g,f){var h=Array.prototype.slice.call(arguments,
2);return function(c,e){e=e||{};return g.apply(this,[c,e.data||f].concat(h))}},program:function(g,f){return function(h,c){c=c||{};return g(h,c.data||f)}},noop:function(){return""},invokePartial:function(g,f,h,c,e,i){c={helpers:c,partials:e,data:i};if(g===undefined)throw new Handlebars.Exception("The partial "+f+" could not be found");else if(g instanceof Function)return g(h,c);else if(Handlebars.compile){e[f]=Handlebars.compile(g,{data:i!==undefined});return e[f](h,c)}else throw new Handlebars.Exception("The partial "+
f+" could not be compiled when running in runtime-only mode");}};Handlebars.template=Handlebars.VM.template;
